// Code generated by '$ fyne bundle'. DO NOT EDIT.

package gui

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed icon_256.png
var appIconData []byte
var appIcon = &fyne.StaticResource{
	StaticName:    "icon_256.png",
	StaticContent: appIconData,
}

//go:embed icon_transcribe.svg
var transcribeIconData []byte
var transcribeIconResource = &fyne.StaticResource{
	StaticName:    "icon_transcribe.svg",
	StaticContent: transcribeIconData,
}

//go:embed icon_mic.svg
var micIconData []byte
var micIconResource = &fyne.StaticResource{
	StaticName:    "icon_mic.svg",
	StaticContent: micIconData,
}

//go:embed icon_play.svg
var playIconData []byte
var playIconResource = &fyne.StaticResource{
	StaticName:    "icon_play.svg",
	StaticContent: playIconData,
}

//go:embed icon_pause.svg
var pauseIconData []byte
var pauseIconResource = &fyne.StaticResource{
	StaticName:    "icon_pause.svg",
	StaticContent: pauseIconData,
}
