// Code generated by '$ fyne bundle'. DO NOT EDIT.

package gui

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed icon_256.png
var appIconData []byte
var appIcon = &fyne.StaticResource{
	StaticName:    "icon_256.png",
	StaticContent: appIconData,
}

//go:embed icon_transcribe.svg
var transcribeIconData []byte
var transcribeIconResource = &fyne.StaticResource{
	StaticName:    "icon_transcribe.svg",
	StaticContent: transcribeIconData,
}

//go:embed icon_expand.svg
var expandIconData []byte
var expandIconResource = &fyne.StaticResource{
	StaticName:    "icon_expand.svg",
	StaticContent: expandIconData,
}
