// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package gui

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed icon_256.png
var appIconData []byte
var appIcon = &fyne.StaticResource{
	StaticName:    "icon_256.png",
	StaticContent: appIconData,
}
